export const kDummyTitles = [
  "Quick Brown Fox",
  "Silent Ocean Waves",
  "Hidden Mountain Trail",
  "Golden Evening Light",
  "Lost City Ruins",
  "Midnight Coding Session",
  "Bright Summer Sky",
  "Rustic Wooden Bridge",
  "Neon City Nights",
  "Ancient Desert Path",
  "Whispering Pine Forest",
  "Falling Autumn Leaves",
  "Crystal Clear Lake",
  "Storm Over Horizon",
  "Quiet Village Morning",
  "Endless Sand Dunes",
  "Frozen Northern Wind",
  "Blooming Spring Garden",
  "Shadows and Lanterns",
  "Last Train Home",
];

export const kDummyLorems = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel ligula scelerisque.",
  "Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Donec sollicitudin molestie malesuada.",
  "Vivamus suscipit tortor eget felis porttitor volutpat. Nulla quis lorem ut libero malesuada feugiat.",
  "Pellentesque in ipsum id orci porta dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices.",
  "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Nulla porttitor accumsan tincidunt.",
  "Donec rutrum congue leo eget malesuada. Cras ultricies ligula sed magna dictum porta.",
  "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
  "Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.",
  "Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui.",
  "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Curabitur aliquet quam id dui posuere.",
  "Quisque velit nisi, pretium ut lacinia in, elementum id enim.",
  "Nulla quis lorem ut libero malesuada feugiat. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a.",
  "Sed porttitor lectus nibh. Donec sollicitudin molestie malesuada. Cras ultricies ligula sed magna dictum porta.",
  "Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Pellentesque in ipsum id orci porta dapibus.",
  "Donec rutrum congue leo eget malesuada. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui.",
  "Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Donec sollicitudin molestie malesuada.",
  "Pellentesque in ipsum id orci porta dapibus. Cras ultricies ligula sed magna dictum porta.",
  "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi.",
  "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Curabitur aliquet quam id dui posuere blandit.",
  "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec velit neque.",
];

export const kDummyToasts: Record<
  "info" | "success" | "warning" | "error",
  string[]
> = {
  info: [
    "Loaded workspace",
    "Fetching latest updates",
    "Opening file: project01.json",
    "Connected to server",
    "Switched to light theme",
    "New plugin detected",
    "Autosave scheduled",
    "Checking dependencies",
    "Opening recent project",
    "Syncing settings",
  ],
  success: [
    "Deleted node N01",
    "Saved file: work01.doc",
    "All work saved",
    "Build completed successfully",
    "Export finished",
    "Configuration updated",
    "Node graph compiled",
    "Plugin installed successfully",
    "Backup created",
    "Workspace restored",
  ],
  warning: [
    "Config not loaded, using default",
    "Connection unstable",
    "Low memory detected",
    "File version mismatch",
    "Plugin deprecated",
    "Unsaved changes detected",
    "Cache nearing limit",
    "API response slow",
    "Storage almost full",
    "Node execution delayed",
  ],
  error: [
    "Failed to load config",
    "Unable to save file",
    "Node execution failed",
    "Plugin installation failed",
    "Connection lost",
    "Invalid project format",
    "Dependency resolution failed",
    "Graph compile error",
    "File write permission denied",
    "Unexpected runtime error",
  ],
};

export const kDummyLogs: Record<"debug" | "info" | "warn" | "error", string[]> =
  {
    debug: [
      "Resolving node dependencies and building execution order for current workflow graph",
      "Calculated new layout bounds after inserting node and updating connected edges",
      "Recomputing derived parameters for node inspector after input field change",
      "Graph store mutation detected and scheduling batched UI update for subscribers",
      "Preparing execution context and allocating runtime buffers for evaluation pass",
      "Plugin registry scan started to locate extensions in configured search paths",
      "Cache lookup completed and returning previously computed node evaluation result",
      "Registering new node instance in graph store with generated deterministic id",
      "Scheduling microtask to flush pending state updates to reactive store",
      "Layout engine recomputed node positions after drag operation completed",
      "Evaluating conditional branch node to determine active downstream edges",
      "Serializing current workflow graph to intermediate structure before export",
      "Scanning plugin manifest fields and validating declared node capabilities",
      "Preparing batched DOM update for graph viewport after multiple node changes",
      "Dispatching graph change event to subscribers registered in editor context",
      "Computed edge routing paths using orthogonal layout strategy for readability",
      "Rebuilding quick search index after plugin nodes were added to registry",
      "Collecting runtime metrics for node execution time and memory usage snapshot",
      "Inspecting node parameter schema to generate dynamic form controls",
      "Validating cached execution result against current node input hash value",
      "Scheduling background worker to evaluate heavy nodes outside UI thread",
      "Resolving plugin dependency graph before initializing extension modules",
      "Mapping persisted node ids to runtime instances during graph restoration",
    ],

    info: [
      "Opening file project01.json and restoring workspace layout from previous session",
      "Connected to development server and synchronizing project resources",
      "Switched editor theme to light mode and updated interface color palette",
      "Loading workflow template and preparing nodes for preview in graph editor",
      "Importing node definitions from installed plugins and updating palette list",
      "Restoring last workspace snapshot and reopening previously active panels",
      "Background sync started to fetch latest project assets from remote storage",
      "Rebuilding project index to improve search results across node definitions",
      "Exporting workflow graph as archive bundle for sharing with collaborators",
      "Initializing plugin sandbox environment and preparing extension runtime",
      "Graph validation started to ensure all required inputs are connected",
      "Loading execution history and reconstructing timeline of recent runs",
      "Scanning workspace directory for newly added files and asset updates",
      "Refreshing node palette to reflect latest plugin installation changes",
      "Downloading schema definitions required for validating workflow parameters",
      "Workspace settings reloaded and applied to editor components",
      "Preparing execution preview and compiling node runtime instructions",
      "Synchronizing keyboard shortcut mappings with user preferences",
      "Generating node thumbnails for visual preview in component browser",
      "Checking network connectivity before starting remote synchronization",
      "Updating internal asset cache with latest metadata from project directory",
      "Graph rendering initialized and viewport controls are ready for interaction",
      "Workspace initialization completed and editor interface is fully loaded",
    ],

    warn: [
      "Large workflow detected and rendering performance may degrade on slower systems",
      "Plugin API version mismatch detected and compatibility mode has been enabled",
      "Configuration file missing optional fields and defaults will be applied",
      "Autosave delayed due to heavy computation during node layout recalculation",
      "Network latency detected and background synchronization may take longer",
      "Deprecated node type used in workflow and migration will be required soon",
      "Graph contains disconnected nodes that will not run during execution",
      "Execution completed but optional outputs were not produced by some nodes",
      "Local cache appears outdated and may not reflect latest remote project state",
      "Node parameter value exceeded recommended range and was automatically clamped",
      "Workspace contains unsaved changes that may be lost if application closes",
      "Plugin loaded with warnings because optional dependencies were unavailable",
      "Temporary files detected from previous sessions and cleanup is recommended",
      "Project uses legacy configuration format which will be removed in future",
      "Execution skipped inactive nodes that were disabled in workflow settings",
      "Background task queue growing large and some operations may be delayed",
      "Remote assets partially loaded due to intermittent network connection",
      "Plugin attempted restricted API access and fallback behavior was used",
      "Execution results may be incomplete because upstream node produced warnings",
      "File path length exceeds recommended limits on some operating systems",
      "Node graph validation reported minor issues that do not block execution",
      "Editor detected high memory usage while rendering large node graphs",
      "Plugin metadata missing optional fields but extension was loaded anyway",
    ],

    error: [
      "Failed to load configuration because file contains invalid JSON structure",
      "Unable to save project file due to insufficient permissions in directory",
      "Node execution failed after receiving invalid input data from upstream node",
      "Plugin installation failed because downloaded package verification failed",
      "Connection to server lost while uploading assets and sync was aborted",
      "Workflow execution stopped because required node dependency was missing",
      "Error parsing project file and workspace state could not be restored",
      "Runtime error occurred while initializing plugin module and it was disabled",
      "Graph engine failed to start because required runtime libraries were missing",
      "Authentication failed while connecting to remote project repository",
      "Execution aborted after detecting cyclic dependency between workflow nodes",
      "Plugin loader encountered unexpected module format and initialization failed",
      "Configuration validation failed because required environment variables missing",
      "Project database could not be opened because storage file appears corrupted",
      "Failed to compile project assets due to syntax errors in configuration",
      "Graph renderer crashed while computing layout for extremely large graphs",
      "Execution environment failed to allocate memory buffers for node processing",
      "Remote asset download failed due to network interruption during transfer",
      "Plugin dependency resolution failed because required package version missing",
      "Unable to restore workspace because saved snapshot data was incomplete",
      "Background synchronization failed due to repeated authentication errors",
      "Node graph validation failed because multiple edges connect to single input",
      "Runtime sandbox terminated plugin after unauthorized file access attempt",
    ],
  };
