export const kDummyTitles = [
  "Quick Brown Fox",
  "Silent Ocean Waves",
  "Hidden Mountain Trail",
  "Golden Evening Light",
  "Lost City Ruins",
  "Midnight Coding Session",
  "Bright Summer Sky",
  "Rustic Wooden Bridge",
  "Neon City Nights",
  "Ancient Desert Path",
  "Whispering Pine Forest",
  "Falling Autumn Leaves",
  "Crystal Clear Lake",
  "Storm Over Horizon",
  "Quiet Village Morning",
  "Endless Sand Dunes",
  "Frozen Northern Wind",
  "Blooming Spring Garden",
  "Shadows and Lanterns",
  "Last Train Home",
];

export const kDummyLorems = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel ligula scelerisque.",
  "Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Donec sollicitudin molestie malesuada.",
  "Vivamus suscipit tortor eget felis porttitor volutpat. Nulla quis lorem ut libero malesuada feugiat.",
  "Pellentesque in ipsum id orci porta dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices.",
  "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Nulla porttitor accumsan tincidunt.",
  "Donec rutrum congue leo eget malesuada. Cras ultricies ligula sed magna dictum porta.",
  "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Proin eget tortor risus.",
  "Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.",
  "Sed porttitor lectus nibh. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui.",
  "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Curabitur aliquet quam id dui posuere.",
  "Quisque velit nisi, pretium ut lacinia in, elementum id enim.",
  "Nulla quis lorem ut libero malesuada feugiat. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a.",
  "Sed porttitor lectus nibh. Donec sollicitudin molestie malesuada. Cras ultricies ligula sed magna dictum porta.",
  "Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Pellentesque in ipsum id orci porta dapibus.",
  "Donec rutrum congue leo eget malesuada. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui.",
  "Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Donec sollicitudin molestie malesuada.",
  "Pellentesque in ipsum id orci porta dapibus. Cras ultricies ligula sed magna dictum porta.",
  "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi.",
  "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Curabitur aliquet quam id dui posuere blandit.",
  "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec velit neque.",
];

export const kDummyToasts: Record<
  "info" | "success" | "warning" | "error",
  string[]
> = {
  info: [
    "Loaded workspace",
    "Fetching latest updates",
    "Opening file: project01.json",
    "Connected to server",
    "Switched to light theme",
    "New plugin detected",
    "Autosave scheduled",
    "Checking dependencies",
    "Opening recent project",
    "Syncing settings",
  ],
  success: [
    "Deleted node N01",
    "Saved file: work01.doc",
    "All work saved",
    "Build completed successfully",
    "Export finished",
    "Configuration updated",
    "Node graph compiled",
    "Plugin installed successfully",
    "Backup created",
    "Workspace restored",
  ],
  warning: [
    "Config not loaded, using default",
    "Connection unstable",
    "Low memory detected",
    "File version mismatch",
    "Plugin deprecated",
    "Unsaved changes detected",
    "Cache nearing limit",
    "API response slow",
    "Storage almost full",
    "Node execution delayed",
  ],
  error: [
    "Failed to load config",
    "Unable to save file",
    "Node execution failed",
    "Plugin installation failed",
    "Connection lost",
    "Invalid project format",
    "Dependency resolution failed",
    "Graph compile error",
    "File write permission denied",
    "Unexpected runtime error",
  ],
};
